# Generated by Django 4.1.5 on 2023-01-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'verbose_name': 'LineaPedido', 'verbose_name_plural': 'LineaPedidos'},
        ),
        migrations.AlterModelTable(
            name='lineapedido',
            table='LineaPedidos',
        ),
    ]
