# Generated by Django 4.1.5 on 2023-01-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_alter_lineapedido_options_alter_lineapedido_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='User_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
