# Generated by Django 4.1.5 on 2023-01-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_rename_user_id_lineapedido_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='User_id',
            new_name='User',
        ),
    ]
