# Generated by Django 4.1.1 on 2022-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='Contenido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='Titulo',
            field=models.CharField(max_length=50),
        ),
    ]
