# Generated by Django 4.1.1 on 2023-01-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Descripcion',
        ),
    ]
